// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package contacting

import (
	"context"
	"gomies/pkg/sdk/types"
	"sync"
)

// Ensure, that ActionsMock does implement Actions.
// If this is not the case, regenerate this file with moq.
var _ Actions = &ActionsMock{}

// ActionsMock is a mock implementation of Actions.
//
// 	func TestSomethingThatUsesActions(t *testing.T) {
//
// 		// make and configure a mocked Actions
// 		mockedActions := &ActionsMock{
// 			GetAddressFunc: func(ctx context.Context, target types.UID, addressID types.UID) (Address, error) {
// 				panic("mock out the GetAddress method")
// 			},
// 			GetPhoneFunc: func(ctx context.Context, target types.UID, id types.UID) (Phone, error) {
// 				panic("mock out the GetPhone method")
// 			},
// 			ListAddressesFunc: func(ctx context.Context, target types.UID) ([]Address, error) {
// 				panic("mock out the ListAddresses method")
// 			},
// 			ListPhonesFunc: func(ctx context.Context, target types.UID) ([]Phone, error) {
// 				panic("mock out the ListPhones method")
// 			},
// 			RemoveAddressFunc: func(ctx context.Context, target types.UID, id types.UID) error {
// 				panic("mock out the RemoveAddress method")
// 			},
// 			RemoveAllAddressesFunc: func(ctx context.Context, target types.UID) error {
// 				panic("mock out the RemoveAllAddresses method")
// 			},
// 			RemoveAllPhonesFunc: func(ctx context.Context, target types.UID) error {
// 				panic("mock out the RemoveAllPhones method")
// 			},
// 			RemovePhoneFunc: func(ctx context.Context, target types.UID, id types.UID) error {
// 				panic("mock out the RemovePhone method")
// 			},
// 			SaveAddressesFunc: func(ctx context.Context, target types.UID, addresses ...Address) ([]Address, error) {
// 				panic("mock out the SaveAddresses method")
// 			},
// 			SavePhonesFunc: func(ctx context.Context, target types.UID, phones ...Address) ([]Phone, error) {
// 				panic("mock out the SavePhones method")
// 			},
// 		}
//
// 		// use mockedActions in code that requires Actions
// 		// and then make assertions.
//
// 	}
type ActionsMock struct {
	// GetAddressFunc mocks the GetAddress method.
	GetAddressFunc func(ctx context.Context, target types.UID, addressID types.UID) (Address, error)

	// GetPhoneFunc mocks the GetPhone method.
	GetPhoneFunc func(ctx context.Context, target types.UID, id types.UID) (Phone, error)

	// ListAddressesFunc mocks the ListAddresses method.
	ListAddressesFunc func(ctx context.Context, target types.UID) ([]Address, error)

	// ListPhonesFunc mocks the ListPhones method.
	ListPhonesFunc func(ctx context.Context, target types.UID) ([]Phone, error)

	// RemoveAddressFunc mocks the RemoveAddress method.
	RemoveAddressFunc func(ctx context.Context, target types.UID, id types.UID) error

	// RemoveAllAddressesFunc mocks the RemoveAllAddresses method.
	RemoveAllAddressesFunc func(ctx context.Context, target types.UID) error

	// RemoveAllPhonesFunc mocks the RemoveAllPhones method.
	RemoveAllPhonesFunc func(ctx context.Context, target types.UID) error

	// RemovePhoneFunc mocks the RemovePhone method.
	RemovePhoneFunc func(ctx context.Context, target types.UID, id types.UID) error

	// SaveAddressesFunc mocks the SaveAddresses method.
	SaveAddressesFunc func(ctx context.Context, target types.UID, addresses ...Address) ([]Address, error)

	// SavePhonesFunc mocks the SavePhones method.
	SavePhonesFunc func(ctx context.Context, target types.UID, phones ...Address) ([]Phone, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetAddress holds details about calls to the GetAddress method.
		GetAddress []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Target is the target argument value.
			Target types.UID
			// AddressID is the addressID argument value.
			AddressID types.UID
		}
		// GetPhone holds details about calls to the GetPhone method.
		GetPhone []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Target is the target argument value.
			Target types.UID
			// ID is the id argument value.
			ID types.UID
		}
		// ListAddresses holds details about calls to the ListAddresses method.
		ListAddresses []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Target is the target argument value.
			Target types.UID
		}
		// ListPhones holds details about calls to the ListPhones method.
		ListPhones []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Target is the target argument value.
			Target types.UID
		}
		// RemoveAddress holds details about calls to the RemoveAddress method.
		RemoveAddress []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Target is the target argument value.
			Target types.UID
			// ID is the id argument value.
			ID types.UID
		}
		// RemoveAllAddresses holds details about calls to the RemoveAllAddresses method.
		RemoveAllAddresses []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Target is the target argument value.
			Target types.UID
		}
		// RemoveAllPhones holds details about calls to the RemoveAllPhones method.
		RemoveAllPhones []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Target is the target argument value.
			Target types.UID
		}
		// RemovePhone holds details about calls to the RemovePhone method.
		RemovePhone []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Target is the target argument value.
			Target types.UID
			// ID is the id argument value.
			ID types.UID
		}
		// SaveAddresses holds details about calls to the SaveAddresses method.
		SaveAddresses []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Target is the target argument value.
			Target types.UID
			// Addresses is the addresses argument value.
			Addresses []Address
		}
		// SavePhones holds details about calls to the SavePhones method.
		SavePhones []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Target is the target argument value.
			Target types.UID
			// Phones is the phones argument value.
			Phones []Address
		}
	}
	lockGetAddress         sync.RWMutex
	lockGetPhone           sync.RWMutex
	lockListAddresses      sync.RWMutex
	lockListPhones         sync.RWMutex
	lockRemoveAddress      sync.RWMutex
	lockRemoveAllAddresses sync.RWMutex
	lockRemoveAllPhones    sync.RWMutex
	lockRemovePhone        sync.RWMutex
	lockSaveAddresses      sync.RWMutex
	lockSavePhones         sync.RWMutex
}

// GetAddress calls GetAddressFunc.
func (mock *ActionsMock) GetAddress(ctx context.Context, target types.UID, addressID types.UID) (Address, error) {
	if mock.GetAddressFunc == nil {
		panic("ActionsMock.GetAddressFunc: method is nil but Actions.GetAddress was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		Target    types.UID
		AddressID types.UID
	}{
		Ctx:       ctx,
		Target:    target,
		AddressID: addressID,
	}
	mock.lockGetAddress.Lock()
	mock.calls.GetAddress = append(mock.calls.GetAddress, callInfo)
	mock.lockGetAddress.Unlock()
	return mock.GetAddressFunc(ctx, target, addressID)
}

// GetAddressCalls gets all the calls that were made to GetAddress.
// Check the length with:
//     len(mockedActions.GetAddressCalls())
func (mock *ActionsMock) GetAddressCalls() []struct {
	Ctx       context.Context
	Target    types.UID
	AddressID types.UID
} {
	var calls []struct {
		Ctx       context.Context
		Target    types.UID
		AddressID types.UID
	}
	mock.lockGetAddress.RLock()
	calls = mock.calls.GetAddress
	mock.lockGetAddress.RUnlock()
	return calls
}

// GetPhone calls GetPhoneFunc.
func (mock *ActionsMock) GetPhone(ctx context.Context, target types.UID, id types.UID) (Phone, error) {
	if mock.GetPhoneFunc == nil {
		panic("ActionsMock.GetPhoneFunc: method is nil but Actions.GetPhone was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Target types.UID
		ID     types.UID
	}{
		Ctx:    ctx,
		Target: target,
		ID:     id,
	}
	mock.lockGetPhone.Lock()
	mock.calls.GetPhone = append(mock.calls.GetPhone, callInfo)
	mock.lockGetPhone.Unlock()
	return mock.GetPhoneFunc(ctx, target, id)
}

// GetPhoneCalls gets all the calls that were made to GetPhone.
// Check the length with:
//     len(mockedActions.GetPhoneCalls())
func (mock *ActionsMock) GetPhoneCalls() []struct {
	Ctx    context.Context
	Target types.UID
	ID     types.UID
} {
	var calls []struct {
		Ctx    context.Context
		Target types.UID
		ID     types.UID
	}
	mock.lockGetPhone.RLock()
	calls = mock.calls.GetPhone
	mock.lockGetPhone.RUnlock()
	return calls
}

// ListAddresses calls ListAddressesFunc.
func (mock *ActionsMock) ListAddresses(ctx context.Context, target types.UID) ([]Address, error) {
	if mock.ListAddressesFunc == nil {
		panic("ActionsMock.ListAddressesFunc: method is nil but Actions.ListAddresses was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Target types.UID
	}{
		Ctx:    ctx,
		Target: target,
	}
	mock.lockListAddresses.Lock()
	mock.calls.ListAddresses = append(mock.calls.ListAddresses, callInfo)
	mock.lockListAddresses.Unlock()
	return mock.ListAddressesFunc(ctx, target)
}

// ListAddressesCalls gets all the calls that were made to ListAddresses.
// Check the length with:
//     len(mockedActions.ListAddressesCalls())
func (mock *ActionsMock) ListAddressesCalls() []struct {
	Ctx    context.Context
	Target types.UID
} {
	var calls []struct {
		Ctx    context.Context
		Target types.UID
	}
	mock.lockListAddresses.RLock()
	calls = mock.calls.ListAddresses
	mock.lockListAddresses.RUnlock()
	return calls
}

// ListPhones calls ListPhonesFunc.
func (mock *ActionsMock) ListPhones(ctx context.Context, target types.UID) ([]Phone, error) {
	if mock.ListPhonesFunc == nil {
		panic("ActionsMock.ListPhonesFunc: method is nil but Actions.ListPhones was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Target types.UID
	}{
		Ctx:    ctx,
		Target: target,
	}
	mock.lockListPhones.Lock()
	mock.calls.ListPhones = append(mock.calls.ListPhones, callInfo)
	mock.lockListPhones.Unlock()
	return mock.ListPhonesFunc(ctx, target)
}

// ListPhonesCalls gets all the calls that were made to ListPhones.
// Check the length with:
//     len(mockedActions.ListPhonesCalls())
func (mock *ActionsMock) ListPhonesCalls() []struct {
	Ctx    context.Context
	Target types.UID
} {
	var calls []struct {
		Ctx    context.Context
		Target types.UID
	}
	mock.lockListPhones.RLock()
	calls = mock.calls.ListPhones
	mock.lockListPhones.RUnlock()
	return calls
}

// RemoveAddress calls RemoveAddressFunc.
func (mock *ActionsMock) RemoveAddress(ctx context.Context, target types.UID, id types.UID) error {
	if mock.RemoveAddressFunc == nil {
		panic("ActionsMock.RemoveAddressFunc: method is nil but Actions.RemoveAddress was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Target types.UID
		ID     types.UID
	}{
		Ctx:    ctx,
		Target: target,
		ID:     id,
	}
	mock.lockRemoveAddress.Lock()
	mock.calls.RemoveAddress = append(mock.calls.RemoveAddress, callInfo)
	mock.lockRemoveAddress.Unlock()
	return mock.RemoveAddressFunc(ctx, target, id)
}

// RemoveAddressCalls gets all the calls that were made to RemoveAddress.
// Check the length with:
//     len(mockedActions.RemoveAddressCalls())
func (mock *ActionsMock) RemoveAddressCalls() []struct {
	Ctx    context.Context
	Target types.UID
	ID     types.UID
} {
	var calls []struct {
		Ctx    context.Context
		Target types.UID
		ID     types.UID
	}
	mock.lockRemoveAddress.RLock()
	calls = mock.calls.RemoveAddress
	mock.lockRemoveAddress.RUnlock()
	return calls
}

// RemoveAllAddresses calls RemoveAllAddressesFunc.
func (mock *ActionsMock) RemoveAllAddresses(ctx context.Context, target types.UID) error {
	if mock.RemoveAllAddressesFunc == nil {
		panic("ActionsMock.RemoveAllAddressesFunc: method is nil but Actions.RemoveAllAddresses was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Target types.UID
	}{
		Ctx:    ctx,
		Target: target,
	}
	mock.lockRemoveAllAddresses.Lock()
	mock.calls.RemoveAllAddresses = append(mock.calls.RemoveAllAddresses, callInfo)
	mock.lockRemoveAllAddresses.Unlock()
	return mock.RemoveAllAddressesFunc(ctx, target)
}

// RemoveAllAddressesCalls gets all the calls that were made to RemoveAllAddresses.
// Check the length with:
//     len(mockedActions.RemoveAllAddressesCalls())
func (mock *ActionsMock) RemoveAllAddressesCalls() []struct {
	Ctx    context.Context
	Target types.UID
} {
	var calls []struct {
		Ctx    context.Context
		Target types.UID
	}
	mock.lockRemoveAllAddresses.RLock()
	calls = mock.calls.RemoveAllAddresses
	mock.lockRemoveAllAddresses.RUnlock()
	return calls
}

// RemoveAllPhones calls RemoveAllPhonesFunc.
func (mock *ActionsMock) RemoveAllPhones(ctx context.Context, target types.UID) error {
	if mock.RemoveAllPhonesFunc == nil {
		panic("ActionsMock.RemoveAllPhonesFunc: method is nil but Actions.RemoveAllPhones was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Target types.UID
	}{
		Ctx:    ctx,
		Target: target,
	}
	mock.lockRemoveAllPhones.Lock()
	mock.calls.RemoveAllPhones = append(mock.calls.RemoveAllPhones, callInfo)
	mock.lockRemoveAllPhones.Unlock()
	return mock.RemoveAllPhonesFunc(ctx, target)
}

// RemoveAllPhonesCalls gets all the calls that were made to RemoveAllPhones.
// Check the length with:
//     len(mockedActions.RemoveAllPhonesCalls())
func (mock *ActionsMock) RemoveAllPhonesCalls() []struct {
	Ctx    context.Context
	Target types.UID
} {
	var calls []struct {
		Ctx    context.Context
		Target types.UID
	}
	mock.lockRemoveAllPhones.RLock()
	calls = mock.calls.RemoveAllPhones
	mock.lockRemoveAllPhones.RUnlock()
	return calls
}

// RemovePhone calls RemovePhoneFunc.
func (mock *ActionsMock) RemovePhone(ctx context.Context, target types.UID, id types.UID) error {
	if mock.RemovePhoneFunc == nil {
		panic("ActionsMock.RemovePhoneFunc: method is nil but Actions.RemovePhone was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Target types.UID
		ID     types.UID
	}{
		Ctx:    ctx,
		Target: target,
		ID:     id,
	}
	mock.lockRemovePhone.Lock()
	mock.calls.RemovePhone = append(mock.calls.RemovePhone, callInfo)
	mock.lockRemovePhone.Unlock()
	return mock.RemovePhoneFunc(ctx, target, id)
}

// RemovePhoneCalls gets all the calls that were made to RemovePhone.
// Check the length with:
//     len(mockedActions.RemovePhoneCalls())
func (mock *ActionsMock) RemovePhoneCalls() []struct {
	Ctx    context.Context
	Target types.UID
	ID     types.UID
} {
	var calls []struct {
		Ctx    context.Context
		Target types.UID
		ID     types.UID
	}
	mock.lockRemovePhone.RLock()
	calls = mock.calls.RemovePhone
	mock.lockRemovePhone.RUnlock()
	return calls
}

// SaveAddresses calls SaveAddressesFunc.
func (mock *ActionsMock) SaveAddresses(ctx context.Context, target types.UID, addresses ...Address) ([]Address, error) {
	if mock.SaveAddressesFunc == nil {
		panic("ActionsMock.SaveAddressesFunc: method is nil but Actions.SaveAddresses was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		Target    types.UID
		Addresses []Address
	}{
		Ctx:       ctx,
		Target:    target,
		Addresses: addresses,
	}
	mock.lockSaveAddresses.Lock()
	mock.calls.SaveAddresses = append(mock.calls.SaveAddresses, callInfo)
	mock.lockSaveAddresses.Unlock()
	return mock.SaveAddressesFunc(ctx, target, addresses...)
}

// SaveAddressesCalls gets all the calls that were made to SaveAddresses.
// Check the length with:
//     len(mockedActions.SaveAddressesCalls())
func (mock *ActionsMock) SaveAddressesCalls() []struct {
	Ctx       context.Context
	Target    types.UID
	Addresses []Address
} {
	var calls []struct {
		Ctx       context.Context
		Target    types.UID
		Addresses []Address
	}
	mock.lockSaveAddresses.RLock()
	calls = mock.calls.SaveAddresses
	mock.lockSaveAddresses.RUnlock()
	return calls
}

// SavePhones calls SavePhonesFunc.
func (mock *ActionsMock) SavePhones(ctx context.Context, target types.UID, phones ...Address) ([]Phone, error) {
	if mock.SavePhonesFunc == nil {
		panic("ActionsMock.SavePhonesFunc: method is nil but Actions.SavePhones was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Target types.UID
		Phones []Address
	}{
		Ctx:    ctx,
		Target: target,
		Phones: phones,
	}
	mock.lockSavePhones.Lock()
	mock.calls.SavePhones = append(mock.calls.SavePhones, callInfo)
	mock.lockSavePhones.Unlock()
	return mock.SavePhonesFunc(ctx, target, phones...)
}

// SavePhonesCalls gets all the calls that were made to SavePhones.
// Check the length with:
//     len(mockedActions.SavePhonesCalls())
func (mock *ActionsMock) SavePhonesCalls() []struct {
	Ctx    context.Context
	Target types.UID
	Phones []Address
} {
	var calls []struct {
		Ctx    context.Context
		Target types.UID
		Phones []Address
	}
	mock.lockSavePhones.RLock()
	calls = mock.calls.SavePhones
	mock.lockSavePhones.RUnlock()
	return calls
}
