// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package category

import (
	"context"
	category2 "gomies/app/core/entities/category"
	"sync"
)

// Ensure, that WorkflowMock does implement Workflow.
// If this is not the case, regenerate this file with moq.
var _ Workflow = &WorkflowMock{}

// WorkflowMock is a mock implementation of Workflow.
//
// 	func TestSomethingThatUsesWorkflow(t *testing.T) {
//
// 		// make and configure a mocked Workflow
// 		mockedWorkflow := &WorkflowMock{
// 			CreateCategoryFunc: func(ctx context.Context, cat category2.Category) (category2.Category, error) {
// 				panic("mock out the CreateCategory method")
// 			},
// 			GetCategoryFunc: func(ctx context.Context, categoryKey category2.Key) (category2.Category, error) {
// 				panic("mock out the GetCategory method")
// 			},
// 			ListCategoriesFunc: func(ctx context.Context, categoryFilter category2.Filter) ([]category2.Category, int, error) {
// 				panic("mock out the ListCategories method")
// 			},
// 			RemoveCategoryFunc: func(ctx context.Context, categoryID category2.Key) error {
// 				panic("mock out the RemoveCategory method")
// 			},
// 			UpdateCategoryFunc: func(ctx context.Context, cat category2.Category) error {
// 				panic("mock out the UpdateCategory method")
// 			},
// 		}
//
// 		// use mockedWorkflow in code that requires Workflow
// 		// and then make assertions.
//
// 	}
type WorkflowMock struct {
	// CreateCategoryFunc mocks the CreateCategory method.
	CreateCategoryFunc func(ctx context.Context, cat category2.Category) (category2.Category, error)

	// GetCategoryFunc mocks the GetCategory method.
	GetCategoryFunc func(ctx context.Context, categoryKey category2.Key) (category2.Category, error)

	// ListCategoriesFunc mocks the ListCategories method.
	ListCategoriesFunc func(ctx context.Context, categoryFilter category2.Filter) ([]category2.Category, int, error)

	// RemoveCategoryFunc mocks the RemoveCategory method.
	RemoveCategoryFunc func(ctx context.Context, categoryID category2.Key) error

	// UpdateCategoryFunc mocks the UpdateCategory method.
	UpdateCategoryFunc func(ctx context.Context, cat category2.Category) error

	// calls tracks calls to the methods.
	calls struct {
		// CreateCategory holds details about calls to the CreateCategory method.
		CreateCategory []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Cat is the cat argument value.
			Cat category2.Category
		}
		// GetCategory holds details about calls to the GetCategory method.
		GetCategory []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// CategoryKey is the categoryKey argument value.
			CategoryKey category2.Key
		}
		// ListCategories holds details about calls to the ListCategories method.
		ListCategories []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// CategoryFilter is the categoryFilter argument value.
			CategoryFilter category2.Filter
		}
		// RemoveCategory holds details about calls to the RemoveCategory method.
		RemoveCategory []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// CategoryID is the categoryID argument value.
			CategoryID category2.Key
		}
		// UpdateCategory holds details about calls to the UpdateCategory method.
		UpdateCategory []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Cat is the cat argument value.
			Cat category2.Category
		}
	}
	lockCreateCategory sync.RWMutex
	lockGetCategory    sync.RWMutex
	lockListCategories sync.RWMutex
	lockRemoveCategory sync.RWMutex
	lockUpdateCategory sync.RWMutex
}

// CreateCategory calls CreateCategoryFunc.
func (mock *WorkflowMock) CreateCategory(ctx context.Context, cat category2.Category) (category2.Category, error) {
	if mock.CreateCategoryFunc == nil {
		panic("WorkflowMock.CreateCategoryFunc: method is nil but Workflow.CreateCategory was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Cat category2.Category
	}{
		Ctx: ctx,
		Cat: cat,
	}
	mock.lockCreateCategory.Lock()
	mock.calls.CreateCategory = append(mock.calls.CreateCategory, callInfo)
	mock.lockCreateCategory.Unlock()
	return mock.CreateCategoryFunc(ctx, cat)
}

// CreateCategoryCalls gets all the calls that were made to CreateCategory.
// Check the length with:
//     len(mockedWorkflow.CreateCategoryCalls())
func (mock *WorkflowMock) CreateCategoryCalls() []struct {
	Ctx context.Context
	Cat category2.Category
} {
	var calls []struct {
		Ctx context.Context
		Cat category2.Category
	}
	mock.lockCreateCategory.RLock()
	calls = mock.calls.CreateCategory
	mock.lockCreateCategory.RUnlock()
	return calls
}

// GetCategory calls GetCategoryFunc.
func (mock *WorkflowMock) GetCategory(ctx context.Context, categoryKey category2.Key) (category2.Category, error) {
	if mock.GetCategoryFunc == nil {
		panic("WorkflowMock.GetCategoryFunc: method is nil but Workflow.GetCategory was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		CategoryKey category2.Key
	}{
		Ctx:         ctx,
		CategoryKey: categoryKey,
	}
	mock.lockGetCategory.Lock()
	mock.calls.GetCategory = append(mock.calls.GetCategory, callInfo)
	mock.lockGetCategory.Unlock()
	return mock.GetCategoryFunc(ctx, categoryKey)
}

// GetCategoryCalls gets all the calls that were made to GetCategory.
// Check the length with:
//     len(mockedWorkflow.GetCategoryCalls())
func (mock *WorkflowMock) GetCategoryCalls() []struct {
	Ctx         context.Context
	CategoryKey category2.Key
} {
	var calls []struct {
		Ctx         context.Context
		CategoryKey category2.Key
	}
	mock.lockGetCategory.RLock()
	calls = mock.calls.GetCategory
	mock.lockGetCategory.RUnlock()
	return calls
}

// ListCategories calls ListCategoriesFunc.
func (mock *WorkflowMock) ListCategories(ctx context.Context, categoryFilter category2.Filter) ([]category2.Category, int, error) {
	if mock.ListCategoriesFunc == nil {
		panic("WorkflowMock.ListCategoriesFunc: method is nil but Workflow.ListCategories was just called")
	}
	callInfo := struct {
		Ctx            context.Context
		CategoryFilter category2.Filter
	}{
		Ctx:            ctx,
		CategoryFilter: categoryFilter,
	}
	mock.lockListCategories.Lock()
	mock.calls.ListCategories = append(mock.calls.ListCategories, callInfo)
	mock.lockListCategories.Unlock()
	return mock.ListCategoriesFunc(ctx, categoryFilter)
}

// ListCategoriesCalls gets all the calls that were made to ListCategories.
// Check the length with:
//     len(mockedWorkflow.ListCategoriesCalls())
func (mock *WorkflowMock) ListCategoriesCalls() []struct {
	Ctx            context.Context
	CategoryFilter category2.Filter
} {
	var calls []struct {
		Ctx            context.Context
		CategoryFilter category2.Filter
	}
	mock.lockListCategories.RLock()
	calls = mock.calls.ListCategories
	mock.lockListCategories.RUnlock()
	return calls
}

// RemoveCategory calls RemoveCategoryFunc.
func (mock *WorkflowMock) RemoveCategory(ctx context.Context, categoryID category2.Key) error {
	if mock.RemoveCategoryFunc == nil {
		panic("WorkflowMock.RemoveCategoryFunc: method is nil but Workflow.RemoveCategory was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		CategoryID category2.Key
	}{
		Ctx:        ctx,
		CategoryID: categoryID,
	}
	mock.lockRemoveCategory.Lock()
	mock.calls.RemoveCategory = append(mock.calls.RemoveCategory, callInfo)
	mock.lockRemoveCategory.Unlock()
	return mock.RemoveCategoryFunc(ctx, categoryID)
}

// RemoveCategoryCalls gets all the calls that were made to RemoveCategory.
// Check the length with:
//     len(mockedWorkflow.RemoveCategoryCalls())
func (mock *WorkflowMock) RemoveCategoryCalls() []struct {
	Ctx        context.Context
	CategoryID category2.Key
} {
	var calls []struct {
		Ctx        context.Context
		CategoryID category2.Key
	}
	mock.lockRemoveCategory.RLock()
	calls = mock.calls.RemoveCategory
	mock.lockRemoveCategory.RUnlock()
	return calls
}

// UpdateCategory calls UpdateCategoryFunc.
func (mock *WorkflowMock) UpdateCategory(ctx context.Context, cat category2.Category) error {
	if mock.UpdateCategoryFunc == nil {
		panic("WorkflowMock.UpdateCategoryFunc: method is nil but Workflow.UpdateCategory was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Cat category2.Category
	}{
		Ctx: ctx,
		Cat: cat,
	}
	mock.lockUpdateCategory.Lock()
	mock.calls.UpdateCategory = append(mock.calls.UpdateCategory, callInfo)
	mock.lockUpdateCategory.Unlock()
	return mock.UpdateCategoryFunc(ctx, cat)
}

// UpdateCategoryCalls gets all the calls that were made to UpdateCategory.
// Check the length with:
//     len(mockedWorkflow.UpdateCategoryCalls())
func (mock *WorkflowMock) UpdateCategoryCalls() []struct {
	Ctx context.Context
	Cat category2.Category
} {
	var calls []struct {
		Ctx context.Context
		Cat category2.Category
	}
	mock.lockUpdateCategory.RLock()
	calls = mock.calls.UpdateCategory
	mock.lockUpdateCategory.RUnlock()
	return calls
}
