name: server
description: A web server built using the shelf package.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  args: ^1.6.0
  comies_entities: ^1.0.5
  jaguar: ^2.4.46
  jaguar_orm: ^2.2.7
  jaguar_reflect: ^2.4.6

dev_dependencies:
  pedantic: ^1.9.0
  build_runner:
  jaguar_orm_gen:
