name: server
description: A web server built using the shelf package.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  args: ^1.6.0
  comies_entities: ^1.0.5
  fluent_query_builder: ^1.1.18

dev_dependencies:
  pedantic: ^1.9.0
