// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package crew

import (
	"context"
	"gomies/pkg/sdk/session"
	"gomies/pkg/sdk/types"
	"sync"
)

// Ensure, that WorkflowMock does implement Workflow.
// If this is not the case, regenerate this file with moq.
var _ Workflow = &WorkflowMock{}

// WorkflowMock is a mock implementation of Workflow.
//
// 	func TestSomethingThatUsesWorkflow(t *testing.T) {
//
// 		// make and configure a mocked Workflow
// 		mockedWorkflow := &WorkflowMock{
// 			AuthenticateFunc: func(ctx context.Context, auth AuthRequest) (session.Session, error) {
// 				panic("mock out the Authenticate method")
// 			},
// 			GetFunc: func(ctx context.Context, key Key) (Member, error) {
// 				panic("mock out the Get method")
// 			},
// 			ListFunc: func(ctx context.Context, operatorFilter Filter) ([]Member, error) {
// 				panic("mock out the List method")
// 			},
// 			RemoveFunc: func(ctx context.Context, key Key) error {
// 				panic("mock out the Remove method")
// 			},
// 			SaveFunc: func(ctx context.Context, op Member, flag ...types.WritingFlag) (Member, error) {
// 				panic("mock out the Save method")
// 			},
// 		}
//
// 		// use mockedWorkflow in code that requires Workflow
// 		// and then make assertions.
//
// 	}
type WorkflowMock struct {
	// AuthenticateFunc mocks the Authenticate method.
	AuthenticateFunc func(ctx context.Context, auth AuthRequest) (session.Session, error)

	// GetFunc mocks the Get method.
	GetFunc func(ctx context.Context, key Key) (Member, error)

	// ListFunc mocks the List method.
	ListFunc func(ctx context.Context, operatorFilter Filter) ([]Member, error)

	// RemoveFunc mocks the Remove method.
	RemoveFunc func(ctx context.Context, key Key) error

	// SaveFunc mocks the Save method.
	SaveFunc func(ctx context.Context, op Member, flag ...types.WritingFlag) (Member, error)

	// calls tracks calls to the methods.
	calls struct {
		// Authenticate holds details about calls to the Authenticate method.
		Authenticate []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Auth is the auth argument value.
			Auth AuthRequest
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Key is the key argument value.
			Key Key
		}
		// List holds details about calls to the List method.
		List []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OperatorFilter is the operatorFilter argument value.
			OperatorFilter Filter
		}
		// Remove holds details about calls to the Remove method.
		Remove []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Key is the key argument value.
			Key Key
		}
		// Save holds details about calls to the Save method.
		Save []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Op is the op argument value.
			Op Member
			// Flag is the flag argument value.
			Flag []types.WritingFlag
		}
	}
	lockAuthenticate sync.RWMutex
	lockGet          sync.RWMutex
	lockList         sync.RWMutex
	lockRemove       sync.RWMutex
	lockSave         sync.RWMutex
}

// Authenticate calls AuthenticateFunc.
func (mock *WorkflowMock) Authenticate(ctx context.Context, auth AuthRequest) (session.Session, error) {
	if mock.AuthenticateFunc == nil {
		panic("WorkflowMock.AuthenticateFunc: method is nil but Workflow.Authenticate was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Auth AuthRequest
	}{
		Ctx:  ctx,
		Auth: auth,
	}
	mock.lockAuthenticate.Lock()
	mock.calls.Authenticate = append(mock.calls.Authenticate, callInfo)
	mock.lockAuthenticate.Unlock()
	return mock.AuthenticateFunc(ctx, auth)
}

// AuthenticateCalls gets all the calls that were made to Authenticate.
// Check the length with:
//     len(mockedWorkflow.AuthenticateCalls())
func (mock *WorkflowMock) AuthenticateCalls() []struct {
	Ctx  context.Context
	Auth AuthRequest
} {
	var calls []struct {
		Ctx  context.Context
		Auth AuthRequest
	}
	mock.lockAuthenticate.RLock()
	calls = mock.calls.Authenticate
	mock.lockAuthenticate.RUnlock()
	return calls
}

// Get calls GetFunc.
func (mock *WorkflowMock) Get(ctx context.Context, key Key) (Member, error) {
	if mock.GetFunc == nil {
		panic("WorkflowMock.GetFunc: method is nil but Workflow.Get was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Key Key
	}{
		Ctx: ctx,
		Key: key,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(ctx, key)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//     len(mockedWorkflow.GetCalls())
func (mock *WorkflowMock) GetCalls() []struct {
	Ctx context.Context
	Key Key
} {
	var calls []struct {
		Ctx context.Context
		Key Key
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// List calls ListFunc.
func (mock *WorkflowMock) List(ctx context.Context, operatorFilter Filter) ([]Member, error) {
	if mock.ListFunc == nil {
		panic("WorkflowMock.ListFunc: method is nil but Workflow.List was just called")
	}
	callInfo := struct {
		Ctx            context.Context
		OperatorFilter Filter
	}{
		Ctx:            ctx,
		OperatorFilter: operatorFilter,
	}
	mock.lockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	mock.lockList.Unlock()
	return mock.ListFunc(ctx, operatorFilter)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//     len(mockedWorkflow.ListCalls())
func (mock *WorkflowMock) ListCalls() []struct {
	Ctx            context.Context
	OperatorFilter Filter
} {
	var calls []struct {
		Ctx            context.Context
		OperatorFilter Filter
	}
	mock.lockList.RLock()
	calls = mock.calls.List
	mock.lockList.RUnlock()
	return calls
}

// Remove calls RemoveFunc.
func (mock *WorkflowMock) Remove(ctx context.Context, key Key) error {
	if mock.RemoveFunc == nil {
		panic("WorkflowMock.RemoveFunc: method is nil but Workflow.Remove was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Key Key
	}{
		Ctx: ctx,
		Key: key,
	}
	mock.lockRemove.Lock()
	mock.calls.Remove = append(mock.calls.Remove, callInfo)
	mock.lockRemove.Unlock()
	return mock.RemoveFunc(ctx, key)
}

// RemoveCalls gets all the calls that were made to Remove.
// Check the length with:
//     len(mockedWorkflow.RemoveCalls())
func (mock *WorkflowMock) RemoveCalls() []struct {
	Ctx context.Context
	Key Key
} {
	var calls []struct {
		Ctx context.Context
		Key Key
	}
	mock.lockRemove.RLock()
	calls = mock.calls.Remove
	mock.lockRemove.RUnlock()
	return calls
}

// Save calls SaveFunc.
func (mock *WorkflowMock) Save(ctx context.Context, op Member, flag ...types.WritingFlag) (Member, error) {
	if mock.SaveFunc == nil {
		panic("WorkflowMock.SaveFunc: method is nil but Workflow.Save was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Op   Member
		Flag []types.WritingFlag
	}{
		Ctx:  ctx,
		Op:   op,
		Flag: flag,
	}
	mock.lockSave.Lock()
	mock.calls.Save = append(mock.calls.Save, callInfo)
	mock.lockSave.Unlock()
	return mock.SaveFunc(ctx, op, flag...)
}

// SaveCalls gets all the calls that were made to Save.
// Check the length with:
//     len(mockedWorkflow.SaveCalls())
func (mock *WorkflowMock) SaveCalls() []struct {
	Ctx  context.Context
	Op   Member
	Flag []types.WritingFlag
} {
	var calls []struct {
		Ctx  context.Context
		Op   Member
		Flag []types.WritingFlag
	}
	mock.lockSave.RLock()
	calls = mock.calls.Save
	mock.lockSave.RUnlock()
	return calls
}
