// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package stock

import (
	"context"
	"gomies/app/core/types/id"
	"sync"
)

// Ensure, that ActionsMock does implement Actions.
// If this is not the case, regenerate this file with moq.
var _ Actions = &ActionsMock{}

// ActionsMock is a mock implementation of Actions.
//
// 	func TestSomethingThatUsesActions(t *testing.T) {
//
// 		// make and configure a mocked Actions
// 		mockedActions := &ActionsMock{
// 			AddToStockFunc: func(contextMoqParam context.Context, movement Movement) (Movement, error) {
// 				panic("mock out the AddToStock method")
// 			},
// 			ComputeStockFunc: func(contextMoqParam context.Context, filter Filter) (Actual, error) {
// 				panic("mock out the ComputeStock method")
// 			},
// 			GetMovementFunc: func(contextMoqParam context.Context, external id.External) (Movement, error) {
// 				panic("mock out the GetMovement method")
// 			},
// 			ListMovementsFunc: func(contextMoqParam context.Context, filter Filter) ([]Movement, error) {
// 				panic("mock out the ListMovements method")
// 			},
// 			RemoveFromStockFunc: func(contextMoqParam context.Context, external id.External) error {
// 				panic("mock out the RemoveFromStock method")
// 			},
// 		}
//
// 		// use mockedActions in code that requires Actions
// 		// and then make assertions.
//
// 	}
type ActionsMock struct {
	// AddToStockFunc mocks the AddToStock method.
	AddToStockFunc func(contextMoqParam context.Context, movement Movement) (Movement, error)

	// ComputeStockFunc mocks the ComputeStock method.
	ComputeStockFunc func(contextMoqParam context.Context, filter Filter) (Actual, error)

	// GetMovementFunc mocks the GetMovement method.
	GetMovementFunc func(contextMoqParam context.Context, external id.External) (Movement, error)

	// ListMovementsFunc mocks the ListMovements method.
	ListMovementsFunc func(contextMoqParam context.Context, filter Filter) ([]Movement, error)

	// RemoveFromStockFunc mocks the RemoveFromStock method.
	RemoveFromStockFunc func(contextMoqParam context.Context, external id.External) error

	// calls tracks calls to the methods.
	calls struct {
		// AddToStock holds details about calls to the AddToStock method.
		AddToStock []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// Movement is the movement argument value.
			Movement Movement
		}
		// ComputeStock holds details about calls to the ComputeStock method.
		ComputeStock []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// Filter is the filter argument value.
			Filter Filter
		}
		// GetMovement holds details about calls to the GetMovement method.
		GetMovement []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// External is the external argument value.
			External id.External
		}
		// ListMovements holds details about calls to the ListMovements method.
		ListMovements []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// Filter is the filter argument value.
			Filter Filter
		}
		// RemoveFromStock holds details about calls to the RemoveFromStock method.
		RemoveFromStock []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// External is the external argument value.
			External id.External
		}
	}
	lockAddToStock      sync.RWMutex
	lockComputeStock    sync.RWMutex
	lockGetMovement     sync.RWMutex
	lockListMovements   sync.RWMutex
	lockRemoveFromStock sync.RWMutex
}

// AddToStock calls AddToStockFunc.
func (mock *ActionsMock) AddToStock(contextMoqParam context.Context, movement Movement) (Movement, error) {
	if mock.AddToStockFunc == nil {
		panic("ActionsMock.AddToStockFunc: method is nil but Actions.AddToStock was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		Movement        Movement
	}{
		ContextMoqParam: contextMoqParam,
		Movement:        movement,
	}
	mock.lockAddToStock.Lock()
	mock.calls.AddToStock = append(mock.calls.AddToStock, callInfo)
	mock.lockAddToStock.Unlock()
	return mock.AddToStockFunc(contextMoqParam, movement)
}

// AddToStockCalls gets all the calls that were made to AddToStock.
// Check the length with:
//     len(mockedActions.AddToStockCalls())
func (mock *ActionsMock) AddToStockCalls() []struct {
	ContextMoqParam context.Context
	Movement        Movement
} {
	var calls []struct {
		ContextMoqParam context.Context
		Movement        Movement
	}
	mock.lockAddToStock.RLock()
	calls = mock.calls.AddToStock
	mock.lockAddToStock.RUnlock()
	return calls
}

// ComputeStock calls ComputeStockFunc.
func (mock *ActionsMock) ComputeStock(contextMoqParam context.Context, filter Filter) (Actual, error) {
	if mock.ComputeStockFunc == nil {
		panic("ActionsMock.ComputeStockFunc: method is nil but Actions.ComputeStock was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		Filter          Filter
	}{
		ContextMoqParam: contextMoqParam,
		Filter:          filter,
	}
	mock.lockComputeStock.Lock()
	mock.calls.ComputeStock = append(mock.calls.ComputeStock, callInfo)
	mock.lockComputeStock.Unlock()
	return mock.ComputeStockFunc(contextMoqParam, filter)
}

// ComputeStockCalls gets all the calls that were made to ComputeStock.
// Check the length with:
//     len(mockedActions.ComputeStockCalls())
func (mock *ActionsMock) ComputeStockCalls() []struct {
	ContextMoqParam context.Context
	Filter          Filter
} {
	var calls []struct {
		ContextMoqParam context.Context
		Filter          Filter
	}
	mock.lockComputeStock.RLock()
	calls = mock.calls.ComputeStock
	mock.lockComputeStock.RUnlock()
	return calls
}

// GetMovement calls GetMovementFunc.
func (mock *ActionsMock) GetMovement(contextMoqParam context.Context, external id.External) (Movement, error) {
	if mock.GetMovementFunc == nil {
		panic("ActionsMock.GetMovementFunc: method is nil but Actions.GetMovement was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		External        id.External
	}{
		ContextMoqParam: contextMoqParam,
		External:        external,
	}
	mock.lockGetMovement.Lock()
	mock.calls.GetMovement = append(mock.calls.GetMovement, callInfo)
	mock.lockGetMovement.Unlock()
	return mock.GetMovementFunc(contextMoqParam, external)
}

// GetMovementCalls gets all the calls that were made to GetMovement.
// Check the length with:
//     len(mockedActions.GetMovementCalls())
func (mock *ActionsMock) GetMovementCalls() []struct {
	ContextMoqParam context.Context
	External        id.External
} {
	var calls []struct {
		ContextMoqParam context.Context
		External        id.External
	}
	mock.lockGetMovement.RLock()
	calls = mock.calls.GetMovement
	mock.lockGetMovement.RUnlock()
	return calls
}

// ListMovements calls ListMovementsFunc.
func (mock *ActionsMock) ListMovements(contextMoqParam context.Context, filter Filter) ([]Movement, error) {
	if mock.ListMovementsFunc == nil {
		panic("ActionsMock.ListMovementsFunc: method is nil but Actions.ListMovements was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		Filter          Filter
	}{
		ContextMoqParam: contextMoqParam,
		Filter:          filter,
	}
	mock.lockListMovements.Lock()
	mock.calls.ListMovements = append(mock.calls.ListMovements, callInfo)
	mock.lockListMovements.Unlock()
	return mock.ListMovementsFunc(contextMoqParam, filter)
}

// ListMovementsCalls gets all the calls that were made to ListMovements.
// Check the length with:
//     len(mockedActions.ListMovementsCalls())
func (mock *ActionsMock) ListMovementsCalls() []struct {
	ContextMoqParam context.Context
	Filter          Filter
} {
	var calls []struct {
		ContextMoqParam context.Context
		Filter          Filter
	}
	mock.lockListMovements.RLock()
	calls = mock.calls.ListMovements
	mock.lockListMovements.RUnlock()
	return calls
}

// RemoveFromStock calls RemoveFromStockFunc.
func (mock *ActionsMock) RemoveFromStock(contextMoqParam context.Context, external id.External) error {
	if mock.RemoveFromStockFunc == nil {
		panic("ActionsMock.RemoveFromStockFunc: method is nil but Actions.RemoveFromStock was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		External        id.External
	}{
		ContextMoqParam: contextMoqParam,
		External:        external,
	}
	mock.lockRemoveFromStock.Lock()
	mock.calls.RemoveFromStock = append(mock.calls.RemoveFromStock, callInfo)
	mock.lockRemoveFromStock.Unlock()
	return mock.RemoveFromStockFunc(contextMoqParam, external)
}

// RemoveFromStockCalls gets all the calls that were made to RemoveFromStock.
// Check the length with:
//     len(mockedActions.RemoveFromStockCalls())
func (mock *ActionsMock) RemoveFromStockCalls() []struct {
	ContextMoqParam context.Context
	External        id.External
} {
	var calls []struct {
		ContextMoqParam context.Context
		External        id.External
	}
	mock.lockRemoveFromStock.RLock()
	calls = mock.calls.RemoveFromStock
	mock.lockRemoveFromStock.RUnlock()
	return calls
}
