// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package crew

import (
	"context"
	"gomies/pkg/sdk/types"
	"sync"
)

// Ensure, that ActionsMock does implement Actions.
// If this is not the case, regenerate this file with moq.
var _ Actions = &ActionsMock{}

// ActionsMock is a mock implementation of Actions.
//
// 	func TestSomethingThatUsesActions(t *testing.T) {
//
// 		// make and configure a mocked Actions
// 		mockedActions := &ActionsMock{
// 			GetFunc: func(ctx context.Context, key Key) (Member, error) {
// 				panic("mock out the Get method")
// 			},
// 			GetWithNicknamesFunc: func(ctx context.Context, operatorNickname string, storeNickname string) (Member, error) {
// 				panic("mock out the GetWithNicknames method")
// 			},
// 			ListFunc: func(ctx context.Context, operatorFilter Filter) ([]Member, error) {
// 				panic("mock out the List method")
// 			},
// 			RemoveFunc: func(ctx context.Context, key Key) error {
// 				panic("mock out the Remove method")
// 			},
// 			SaveFunc: func(ctx context.Context, op Member, flag ...types.WritingFlag) (Member, error) {
// 				panic("mock out the Save method")
// 			},
// 		}
//
// 		// use mockedActions in code that requires Actions
// 		// and then make assertions.
//
// 	}
type ActionsMock struct {
	// GetFunc mocks the Get method.
	GetFunc func(ctx context.Context, key Key) (Member, error)

	// GetWithNicknamesFunc mocks the GetWithNicknames method.
	GetWithNicknamesFunc func(ctx context.Context, operatorNickname string, storeNickname string) (Member, error)

	// ListFunc mocks the List method.
	ListFunc func(ctx context.Context, operatorFilter Filter) ([]Member, error)

	// RemoveFunc mocks the Remove method.
	RemoveFunc func(ctx context.Context, key Key) error

	// SaveFunc mocks the Save method.
	SaveFunc func(ctx context.Context, op Member, flag ...types.WritingFlag) (Member, error)

	// calls tracks calls to the methods.
	calls struct {
		// Get holds details about calls to the Get method.
		Get []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Key is the key argument value.
			Key Key
		}
		// GetWithNicknames holds details about calls to the GetWithNicknames method.
		GetWithNicknames []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OperatorNickname is the operatorNickname argument value.
			OperatorNickname string
			// StoreNickname is the storeNickname argument value.
			StoreNickname string
		}
		// List holds details about calls to the List method.
		List []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OperatorFilter is the operatorFilter argument value.
			OperatorFilter Filter
		}
		// Remove holds details about calls to the Remove method.
		Remove []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Key is the key argument value.
			Key Key
		}
		// Save holds details about calls to the Save method.
		Save []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Op is the op argument value.
			Op Member
			// Flag is the flag argument value.
			Flag []types.WritingFlag
		}
	}
	lockGet              sync.RWMutex
	lockGetWithNicknames sync.RWMutex
	lockList             sync.RWMutex
	lockRemove           sync.RWMutex
	lockSave             sync.RWMutex
}

// Get calls GetFunc.
func (mock *ActionsMock) Get(ctx context.Context, key Key) (Member, error) {
	if mock.GetFunc == nil {
		panic("ActionsMock.GetFunc: method is nil but Actions.Get was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Key Key
	}{
		Ctx: ctx,
		Key: key,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(ctx, key)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//     len(mockedActions.GetCalls())
func (mock *ActionsMock) GetCalls() []struct {
	Ctx context.Context
	Key Key
} {
	var calls []struct {
		Ctx context.Context
		Key Key
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// GetWithNicknames calls GetWithNicknamesFunc.
func (mock *ActionsMock) GetWithNicknames(ctx context.Context, operatorNickname string, storeNickname string) (Member, error) {
	if mock.GetWithNicknamesFunc == nil {
		panic("ActionsMock.GetWithNicknamesFunc: method is nil but Actions.GetWithNicknames was just called")
	}
	callInfo := struct {
		Ctx              context.Context
		OperatorNickname string
		StoreNickname    string
	}{
		Ctx:              ctx,
		OperatorNickname: operatorNickname,
		StoreNickname:    storeNickname,
	}
	mock.lockGetWithNicknames.Lock()
	mock.calls.GetWithNicknames = append(mock.calls.GetWithNicknames, callInfo)
	mock.lockGetWithNicknames.Unlock()
	return mock.GetWithNicknamesFunc(ctx, operatorNickname, storeNickname)
}

// GetWithNicknamesCalls gets all the calls that were made to GetWithNicknames.
// Check the length with:
//     len(mockedActions.GetWithNicknamesCalls())
func (mock *ActionsMock) GetWithNicknamesCalls() []struct {
	Ctx              context.Context
	OperatorNickname string
	StoreNickname    string
} {
	var calls []struct {
		Ctx              context.Context
		OperatorNickname string
		StoreNickname    string
	}
	mock.lockGetWithNicknames.RLock()
	calls = mock.calls.GetWithNicknames
	mock.lockGetWithNicknames.RUnlock()
	return calls
}

// List calls ListFunc.
func (mock *ActionsMock) List(ctx context.Context, operatorFilter Filter) ([]Member, error) {
	if mock.ListFunc == nil {
		panic("ActionsMock.ListFunc: method is nil but Actions.List was just called")
	}
	callInfo := struct {
		Ctx            context.Context
		OperatorFilter Filter
	}{
		Ctx:            ctx,
		OperatorFilter: operatorFilter,
	}
	mock.lockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	mock.lockList.Unlock()
	return mock.ListFunc(ctx, operatorFilter)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//     len(mockedActions.ListCalls())
func (mock *ActionsMock) ListCalls() []struct {
	Ctx            context.Context
	OperatorFilter Filter
} {
	var calls []struct {
		Ctx            context.Context
		OperatorFilter Filter
	}
	mock.lockList.RLock()
	calls = mock.calls.List
	mock.lockList.RUnlock()
	return calls
}

// Remove calls RemoveFunc.
func (mock *ActionsMock) Remove(ctx context.Context, key Key) error {
	if mock.RemoveFunc == nil {
		panic("ActionsMock.RemoveFunc: method is nil but Actions.Remove was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Key Key
	}{
		Ctx: ctx,
		Key: key,
	}
	mock.lockRemove.Lock()
	mock.calls.Remove = append(mock.calls.Remove, callInfo)
	mock.lockRemove.Unlock()
	return mock.RemoveFunc(ctx, key)
}

// RemoveCalls gets all the calls that were made to Remove.
// Check the length with:
//     len(mockedActions.RemoveCalls())
func (mock *ActionsMock) RemoveCalls() []struct {
	Ctx context.Context
	Key Key
} {
	var calls []struct {
		Ctx context.Context
		Key Key
	}
	mock.lockRemove.RLock()
	calls = mock.calls.Remove
	mock.lockRemove.RUnlock()
	return calls
}

// Save calls SaveFunc.
func (mock *ActionsMock) Save(ctx context.Context, op Member, flag ...types.WritingFlag) (Member, error) {
	if mock.SaveFunc == nil {
		panic("ActionsMock.SaveFunc: method is nil but Actions.Save was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Op   Member
		Flag []types.WritingFlag
	}{
		Ctx:  ctx,
		Op:   op,
		Flag: flag,
	}
	mock.lockSave.Lock()
	mock.calls.Save = append(mock.calls.Save, callInfo)
	mock.lockSave.Unlock()
	return mock.SaveFunc(ctx, op, flag...)
}

// SaveCalls gets all the calls that were made to Save.
// Check the length with:
//     len(mockedActions.SaveCalls())
func (mock *ActionsMock) SaveCalls() []struct {
	Ctx  context.Context
	Op   Member
	Flag []types.WritingFlag
} {
	var calls []struct {
		Ctx  context.Context
		Op   Member
		Flag []types.WritingFlag
	}
	mock.lockSave.RLock()
	calls = mock.calls.Save
	mock.lockSave.RUnlock()
	return calls
}
